### ISSUE TITLE
[unavavailable] for some time - since 1.18

### ISSUE THREAD

**Issue by gkathan** [patman15/BMS_BLE-HA#388]
### Checklist

- [x] I have tried the latest version of BMS_BLE-HA.
- [x] I have enabled debug logging for my installation.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issue](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3Abug).
- [x] I have filled out the issue template to the best of my ability.

### Provide the type of BMS you used:

offgridtect smartbatt (OGT) 

### Describe the issue

hi patrick,
if you remember - we two did the iontegratrion for my offgridtec smartbatt back 1 year ago or so ... cannot remember whether mine is a typa A or type B ...
your integration worked rock solid till i installed 1.18 - from then on i have regular "unavailable" messages for a cycle of 30-60 seconds and then again values 
any ideas ?`
cheerz

### Reproduction steps

```text
1.
2.
3.
...
```

### Debug logs

cannot find option to enable debug logging on your hacs integration

**Comment by patman15** [comment]
I have 1.18 running with my type B battery without any issues, which actually doesn't mean much. 😎 I need a debug log to be able to say more.

> cannot find option to enable debug logging on your hacs integration

Why not? Did you follow the [instructions](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics)? Should be there as soon as you have at least 1 battery active.

**Comment by Tulexcorp** [comment]
Having the same issues with the last update with my Seplos V2 batteries.
Some batteries more than others. 
I used to get the occasional unavailable, but nothing like this. Graphing my delta, I never saw gaps. Now, it looks like a dot to dot.

[home-assistant_bms_ble_2025-07-11T05-14-56.261Z.log](https://github.com/user-attachments/files/21175440/home-assistant_bms_ble_2025-07-11T05-14-56.261Z.log)

**Comment by Tulexcorp** [comment]
As to the logging, the whole device page has changed, at least for me. Logging is now done with the 3 dots top right.

**Comment by patman15** [comment]
@Tulexcorp 
> Having the same issues with the last update with my Seplos V2 batteries.

Checked your log, this is indeed an issue for your type of batteries. I'll do a fix and provide you a test version. If it's troubling you, you can downgrade via HACS in the meanwhile.

> As to the logging, the whole device page has changed, at least for me. 

That is the update to HA 2025.7, not related to the integration update.

**Comment by Tulexcorp** [comment]
Hi  Pat,

I'll just wait for the fix, I'm likely to mess things up downgrading. 

For logging, I meant across the board. We can't see info for any integrations. I hadn't been to that area in settings since the last few updates, so it was a bit of a shock to not be able to log the way we could in the past.

**Comment by patman15** [comment]
@Tulexcorp there are two issues actually. I fixed the first in the [branch linked to this ticket](https://github.com/patman15/BMS_BLE-HA/tree/388-seplos-v2-double-response---since-118). Could you try it via [manual install](https://github.com/patman15/BMS_BLE-HA?tab=readme-ov-file#installation) please? I will fix a second issue a soon as you confirm the first is gone. So I would kindly ask you for a second test then.

**Comment by Tulexcorp** [comment]
Installed. Log attached.

Hopefully these are real issues you found and not caused by something on my end. After sending the previous log, I rebooted HA. While I did still get the occasional unavailable, it was nowhere near as bad.

[home-assistant_bms_ble_2025-07-12T15-31-39.007Z.log](https://github.com/user-attachments/files/21197064/home-assistant_bms_ble_2025-07-12T15-31-39.007Z.log)

**Comment by patman15** [comment]
> Hopefully these are real issues you found and not caused by something on my end. 

No these are real issues that surfaced due to a change I need to do for other BMSs. I did another small fix, can you check again? This is very helpful!

**Comment by Tulexcorp** [comment]
Installed, log attached.

[home-assistant_bms_ble_2025-07-12T16-27-09.658Z.log](https://github.com/user-attachments/files/21197292/home-assistant_bms_ble_2025-07-12T16-27-09.658Z.log)

**Comment by patman15** [comment]
Looks good to me. I don't see any missed requests anymore. What's your impression?

**Comment by Tulexcorp** [comment]
I let it run for an hour, looks pretty good. I think Seplos has it's own issues with BT, but when I do see unavailable, they don't last as long as they did in the past, seems like about 30 sec now. From my graph over an hour - 

Battery - Number of Unavailable - Signal Strength - Link Quality
1 - 1 - 85 - 99
2 - 0 - 85 - 100
3 - 2 - 86 - 97
4 - 2 - 79 - 98
5 - 0 - 80 - 100
6 - 0 - 89 - 100

**Comment by patman15** [comment]
@Tulexcorp for the `RSSI` level this is amazingly good. That's fine now.
@gkathan what about you? Did your issue resolve?

**Comment by gkathan** [comment]
here we go ... more and more suspect it's some sort of Bluetooth ble issue cause sometimes also my victron devices show also being unavailable shortly ...
```
    ...sorry currently on the road & cannot tinker around ;-) hope there will be an hacs update soon 💚

**Comment by patman15** [comment]
Should I do a new patch release? Without log files I cannot fix something specific for you. I don't think there is a high chance that the fixes so far affect the OGT BMS as well. Just saying ...

**Comment by patman15** [comment]
@gkathan I merged some changes for version 1.18.1. In case you still have issues with your setup, please open a new issue and attach a log. I hope that some of the changes in 1.18.1 still help you.

**Comment by gkathan** [comment]
will try thanx sooo much
