### ISSUE TITLE
Renogy BMS not recognized

### ISSUE THREAD

**Issue by thecodingmax** [patman15/BMS_BLE-HA#390]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate of any [previous enhancement requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue%20label%3Aenhancement%20OR%20label%3A%22new%20device%22).
- [x] I have checked out the latest <a href="https://github.com/patman15/BMS_BLE-HA/releases">![GitHub Release](https://img.shields.io/github/v/release/patman15/BMS_BLE-HA?include_prereleases&style=social)</a>

### Please describe the enhancement you would like to have.

The integration setup process does not find my Renogy BMS. I have tried all the suggestions listed on the integrations documentation, with no success. My Bluetooth Adapter is a Sabrent BT-UB40 (CSR8510A10) listed under Known working high-performance adapters on the Bluetooth Integration page. RSSI was around -45. The registration of the battery in the Renogy app has been removed beforehand. 

### Additional context

{"name":"RNGRBP1228000830","address":"4C:E1:74:57:94:7B","rssi":-44,"manufacturer_data":{"57676":"7457947b"},"service_data":{},"service_uuids":[],"source":"00:1A:7D:DA:71:13","connectable":true,"time":1751988349.1528392,"tx_power":null}

**Comment by patman15** [comment]
Hi @thecodingmax ! Thanks for the excellent preparation and report!
Can you please try the [branch linked to this ticket](https://github.com/patman15/BMS_BLE-HA/tree/390-renogy-bms-not-recognized) via [manual install](https://github.com/patman15/BMS_BLE-HA#installation)? I have some fear that this battery uses a different BMS type, but let's see.

**Comment by thecodingmax** [comment]
![Image](https://github.com/user-attachments/assets/642f2f13-6121-4e04-924f-726a275ff71d)

Hi @patman15, looks like we are really close, the battery gets recognized now, but there is an error (see screenshot attachment). Thanks for your effort!

**Comment by patman15** [comment]
@thecodingmax 🤔 not sure. This should not happen and hints towards Renogy changed the BMS type. Can you run the [service explorer script](https://github.com/hbldh/bleak/blob/develop/examples/service_explorer.py) on some Linux and provide me the output?

**Comment by thecodingmax** [comment]
@patman15 here comes the output.

[log.txt](https://github.com/user-attachments/files/21129848/log.txt)

**Comment by patman15** [comment]
@thecodingmax Hmm, now I'm 99% sure, I will need to do a new protocol implementation for this battery. Please see if you are able to capture the Bluetooth traffic on [Android](https://www.caichinger.com/blog/2020/11/08/capture_bluetooth_traffic_from_android/) or [iOS](https://novelbits.io/debugging-sniffing-secure-ble-ios/) while using the vendor app with the battery. I can then have a look and put the protocol on my backlog. Won't happen today anymore. :wink:

**Comment by thecodingmax** [comment]
@patman15 alrighty i will try to capture some traffic. Pretty interesting for me as i just have successfully reverse engineered a dometic cfx 335 cooling box, which was my first experience with bluetooth stuff and even creating a homeassistant integration on my own. Thank you very much for your effort, have a good one 👍

**Comment by patman15** [comment]
@thecodingmax also a cool project 👍 If you are pro, help is always welcome, see [contributing guidelines](https://github.com/patman15/BMS_BLE-HA/blob/main/CONTRIBUTING.md). But I'm also happy about people providing input and testing. Have a good one as well!

**Comment by thecodingmax** [comment]
@patman15 Hmmmm unfortunately it seems that the BMS only accepts one bluetooth connection at a time. As long as I am connected via the app I can not establish a connection with nRF on my tablet and vice versa. As i am a newbie to this bluetooth stuff i am already out of options 😔 Can i provide some helpful info from the nRF app log? If so, could you help me with some specific requirements?

**Comment by patman15** [comment]
@thecodingmax please follow the links in my [previous comment](https://github.com/patman15/BMS_BLE-HA/issues/390#issuecomment-3050055881). The instructions should tell you how to record traffic on the device you are using with the battery (app).

**Comment by thecodingmax** [comment]
@patman15 I received an android app called device utils from renogy yesterday to extract the battery' history logs. There are also a few other categories to export in this app, I have attached all gathered information. Do you mind having a look if this provides sufficient information? Best regards 🙏

[battery.xls](https://github.com/user-attachments/files/21201398/battery.xls)
[controller.xls](https://github.com/user-attachments/files/21201396/controller.xls)
[dcc.xls](https://github.com/user-attachments/files/21201397/dcc.xls)
[inverter.xls](https://github.com/user-attachments/files/21201399/inverter.xls)

**Comment by patman15** [comment]
Hmm, that was actually not what I was looking for, but I think this fulfills my needs to get it going. 👍 Also I see that the protocol does not seem to be too different from the one I already have, so a modification shouldn't be complicate. Give me a week or so ...

**Comment by thecodingmax** [comment]
@patman15 perfect, thank you very much for your patience and your efforts. 🙏

**Comment by patman15** [comment]
@thecodingmax if you are adventurous (had no time to write tests yet) you can try the [branch linked to this ticket](https://github.com/patman15/BMS_BLE-HA/tree/390-renogy-bms-not-recognized) via [manual install](https://github.com/patman15/BMS_BLE-HA/tree/390-renogy-bms-not-recognized?tab=readme-ov-file#installation). In case you do so, please provide me a debug log of a few minutes so I can write regression tests to keep future versions compatible. Thanks!

**Comment by thecodingmax** [comment]
Hi @patman15, thank you for the update. Unfortunately i am not able to connect the integration to my battery. The setup process terminates with a ble timeout. I did several connection resets by deleting the battery from the renogy app, disconnected all loads, plugged in a charger and connected to the battery again. In the app it works every single time. But unfortunately not in the integration. Not sure if i am doing something wrong on my end. Debug log is attached.
Best regards 
Max

[home-assistant.log](https://github.com/user-attachments/files/21334844/home-assistant.log)

**Comment by patman15** [comment]
@thecodingmax no, not you are doing something wrong, the BT properties of this device are totally messed up. BT uses UUID (Universally Unique Identifier), but for this device they are neither universal nor unique. 😞 I added fix, maybe you can try again with the updated code?

**Comment by thecodingmax** [comment]
@patman15 I have tested the fix, unfortunately there are other errors occurring in the logs right now. 

[home-assistant.log](https://github.com/user-attachments/files/21335377/home-assistant.log)

**Comment by patman15** [comment]
@thecodingmax Sorry, stupid copy&paste error. fixed.

**Comment by thecodingmax** [comment]
@patman15 You are the man 😁👍 The connection is successfully established and I have several values in Homeassistant, thank you very very much 🙏 

![Image](https://github.com/user-attachments/assets/f7132ed6-76c1-4e33-ae65-bc8500cc8c59)

Just one strange observation: Some values as the current and the power seem to be represented by (actual value/10)? Also the SoC is weird by showing 445% or something... I mean for current and power I can set up a template sensor with factor 10, but this strange SoC value? Do you have any idea what is happening here?

**Comment by patman15** [comment]
> Do you have any idea what is happening here?

Sure, there is still some difference between your BMS and the one I cloned from (also Renogy). Obviously they changed the data format somehow. Can you provide me a log file and a a screenshot from the app timely close to each other? You can simply deactivate the device in HA to get access via the app. This way I can compare the values and fix it, no need for template sensors.

**Comment by thecodingmax** [comment]
Ah ok, understand. So here are app-data and homeassistant-data with a time difference of < 4 minutes. 

[home-assistant.log](https://github.com/user-attachments/files/21335933/home-assistant.log)

![Image](https://github.com/user-attachments/assets/c742b453-3984-4afe-a3b0-4ed05c8ffc69)

**Comment by patman15** [comment]
Ok, and you are sure the app is correct regarding the amps?
Reason I ask is that your log from https://github.com/patman15/BMS_BLE-HA/issues/390#issuecomment-3066156307 says otherwise, i.e. `bat#battery_amps#percentiles_coefficient` which means `/100` and not `/10` as the app ...

**Comment by thecodingmax** [comment]
Yes with regard to current and power i am absolutely sure the values are correct (at least when it comes to the decimal place). At the moment i use a victron shunt for measuring current and power and it delivers very much the same values.

**Comment by patman15** [comment]
@thecodingmax ok, you found a really stupid bug in the battery level calculation, no idea, how that could stay for so long. That and the current is fixed, which also fixes power. Should be good now.

**Comment by thecodingmax** [comment]
The battery level looks good now, but for power and current it is still the same 🤔

![Image](https://github.com/user-attachments/assets/a17aaabb-483f-4f66-a38c-dbd3f352b641)

**Comment by thecodingmax** [comment]
Also the estimated remaining time is 10 times the value you would expect, but I guess this correlates to the wrong decimal place of current/power...

**Comment by patman15** [comment]
@thecodingmax my mistake, finally fixed and tested. I'm still unhappy with the code but it should work for you.

**Comment by thecodingmax** [comment]
Alright, working perfect now, so at least one of us is very happy now 😁 Thank you very much for your work @patman15, I really appreciate it 🙏 All the best for you.
